### ISSUE TITLE
No xamarin compatibility

### ISSUE THREAD

**Issue by smarongiu** [Dresel/MethodCache#10]
It's a pity the last package does not work in Xamarin PCL projects (.net profile78). Annotation is not recognized. 
Do you have some glue to let it work ?

**Comment by Dresel** [comment]
With last package you mean that previous packages (1.3.2 for example) are working?

**Comment by Dresel** [comment]
Maybe @SimonCropp has more information about this?

**Comment by SimonCropp** [comment]
looking at the current nuget it only supports `net40` so no way it will work in xamarin

**Comment by Dresel** [comment]
Thanks for your answer, even if it might seem obvious to you.

I just scanned over some of your nuget package to find some guidance.

Would it be enough to add the same dll (MethodCache targets 4.0) to a "portable-net4+sl5+wpa81+wp8+win8+MonoAndroid16+MonoTouch40" folder in the nuget package? Or are there other constraints I have to take care of?

**Comment by smarongiu** [comment]
Actual xamarin pcl projects are based on profile 78 == portable-net45+netcore45+wp8.
I don't know if your net40 target is enough

**Comment by SimonCropp** [comment]
isnt `portable-net45` a super set of `portable-net4` so it should work

**Comment by Dresel** [comment]
Maybe my statement was a little bit misleading / incorrect.

The reference added to the project is MethodCache.Attributes.dll, which is a portable library (.NET Framework 4, Silverlight 5, Windows 8, Windows Phone Silverlight 8 - Windows Phone 8.1 and DNX Core are not checked). This is the .dll currently in the net40 nuget package folder.

The MethodCache.Fody.dll, which is used for weaving, targets .net 40, but as far as I understand that shouldn't be relevant?

**Comment by SimonCropp** [comment]
> MethodCache.Fody.dll, which is used for weaving, targets .net 40, 

correct the target runtime of the weaver has no impact on the assemblies it can process

**Comment by Dresel** [comment]
Well if it would be so easy. I'm using Debug.WriteLine which are not always in the System assembly.

Would you consider [ReferenceFinder](https://github.com/Fody/MethodTimer/blob/master/Fody/ReferenceFinder.cs) from your MethodTimer assembly best practice for resolving this issue?

**Comment by SimonCropp** [comment]
yep that should work for you

**Comment by smarongiu** [comment]
For information, in my pcl project MethodCache.Fody is installed without errors, but after adding the "using MethodCache.Attributes" statement to the source file in order to use [Cache] annotation I get the message : "Error CS0246: The type or namespace name `MethodCache' could not be found. Are you missing an assembly reference? (CS0246)"

**Comment by Dresel** [comment]
I uploaded a new version, try

   Install-Package MethodCache.Fody -Version 1.4.1-alpha2

and tell me your results.

**Comment by smarongiu** [comment]
Thank you.
Now package is installing without problems and attribute is working, but I got an exception when building :
------
Error: Fody: An unhandled exception occurred:
Exception:
Object reference not set to an instance of an object
StackTrace:
  at MethodCache.Fody.CecilHelper.ContainsAttribute (ICustomAttributeProvider methodDefinition, System.Type attributeType) <0x40d81b0 + 0x0004e> in <filename unknown>:0 
  at MethodCache.Fody.ModuleWeaver.ShouldWeaveProperty (Mono.Cecil.PropertyDefinition property) <0x40da060 + 0x001c3> in <filename unknown>:0 
  at MethodCache.Fody.ModuleWeaver.SelectMethods () <0x40d5e18 + 0x001e3> in <filename unknown>:0 
  at MethodCache.Fody.ModuleWeaver.Execute () <0x40c7378 + 0x0016f> in <filename unknown>:0 
  at (wrapper dynamic-method) System.Object:lambda_method (System.Runtime.CompilerServices.Closure,object)
  at InnerWeaver.ExecuteWeavers () <0x40c6f00 + 0x001b0> in <filename unknown>:0 
  at InnerWeaver.Execute () <0x4051860 + 0x000df> in <filename unknown>:0 
Source:
MethodCache.Fody
TargetSite:
Boolean ContainsAttribute(Mono.Cecil.ICustomAttributeProvider, System.Type)
 (my pcl project)

**Comment by Dresel** [comment]
Can you upload a repo of your project?

**Comment by smarongiu** [comment]
I'm not allowed to share that projet, so I will try to reproduce this error in a fresh solution I can upload. I'm working on OSX, with Xamarin Studio Enterprise. My project is a Forms based application targeting ios&android, with PCL shared code.

**Comment by Dresel** [comment]
I think I know whats wrong - will upload a new version when I'm finished.

**Comment by Dresel** [comment]
Try once again:

    Install-Package MethodCache.Fody -Version 1.4.1-alpha3

**Comment by smarongiu** [comment]
Cool! it seems to work with alpha3 version. I uploaded a sample solution to https://github.com/smarongiu/MethodCacheXamarinSample.
I'm going to make some test in my real project before closing the issue.

**Comment by Dresel** [comment]
Did you have time to test it out?

**Comment by smarongiu** [comment]
Yes, I close this issue. Hope you will publish the fix to master soon.
Thank you.
