### ISSUE TITLE
Uncaught exception on auto-generated read-only property

### ISSUE THREAD

**Issue by onate** [Dresel/MethodCache#11]
If I try to run this on a class that contains an auto-generated read-only property (ie. no setter), it fails with an uncaught exception.  The problem appears to be in the file MethodCache.Fody/ModuleWeaver.cs line 438:

bool hasSetAccessor = property.GetMethod != null;

Should be:

bool hasSetAccessor = property.SetMethod != null;

**Comment by Dresel** [comment]
This should be fixed in 1.4.3, please try

    Install-Package MethodCache.Fody -Version 1.4.1-alpha3

and tell me if it works.

**Comment by onate** [comment]
That fixed it.  Thanks.

**Comment by Dresel** [comment]
Fixed in `1.4.1`.
