### ISSUE TITLE
FodyHelpers >= 3.0.0

### ISSUE THREAD

**Issue by Venipa** [Dresel/MethodCache#16]
Mind upgrading ur FodyHelpers to >= 3.0.0?

Getting this with ur latest Alpha1:
```Fody: The weaver assembly 'MethodCache.Fody, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' references an out of date version of Mono.Cecil.dll. Expected strong name token of '1C-A0-91-87-7D-12-CA-03' but got '50-CE-BF-1C-CE-B9-D0-5E'. The weaver needs to update to at least version 3.0 of FodyHelpers.```

**Comment by Dresel** [comment]
There are more changes required than expected, give me some time.

**Comment by Dresel** [comment]
We have made a complete rewrite of MethodCache that supports latest version of Fody . Please find the new version [here](https://github.com/SpatialFocus/MethodCache.Fody/).
