### ISSUE TITLE
[question] Is this project still alive?

### ISSUE THREAD

**Issue by brud** [Dresel/MethodCache#18]
Or any alternatives for it?

**Comment by Dresel** [comment]
Migration to a current Fody version is on my backlog, but I can't promise anything.

**Comment by Dresel** [comment]
You might want to evaluate https://github.com/clawit/Cache.

**Comment by Dresel** [comment]
We have made a complete rewrite of MethodCache that supports latest version of Fody . Please find the new version [here](https://github.com/SpatialFocus/MethodCache.Fody/).
