### ISSUE TITLE
Problem when using MethodCache on a 3.5 assembly

### ISSUE THREAD

**Issue by bakakamo** [Dresel/MethodCache#8]
Hello,

When using MethodCache on a 3.5 assembly, a reference to mscorlib 4.0 seems to be added to the assembly.

If the debug messages are enabled, a reference to System 4.0 is added too, and I get a FileNotFoundException saying that System 4.0 can't be found.

I'm not sure if older versions of .NET are supported or not, so maybe it is just a matter of indicating it in the readme.

Best regards.

**Comment by Dresel** [comment]
Fixed in `1.4.1`.
